<%@ Page Title="" Language="C#" MasterPageFile="~/masterpages/frontend.master" AutoEventWireup="true" CodeFile="privacy-fr.aspx.cs" Inherits="privacy_fr" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="contentBreadcrumb" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="contentMain" Runat="Server">
      <div class="privacypolicy">
        <h1>Politique relative à la protection des données à caractère personnel</h1>
        <p>
       La présente Politique détaille la manière dont nous recueillons, conservons et utilisons les informations relatives aux personnes. Elle s’applique uniquement aux données recueillies par nos soins à partir de documents en ligne affichant un lien vers la présente Politique, et en aucun cas à partir d’une autre source. VOTRE UTILISATION DE CE SITE INTERNET IMPLIQUE VOTRE CONSENTEMENT À LA COLLECTE ET À L’UTILISATION DE VOS DONNÉES CONFORMÉMENT À LA PRÉSENTE POLITIQUE. VOUS RECONNAISSEZ ÉGALEMENT QUE NOUS POUVONS CHANGER, MODIFIER, ACTUALISER CETTE POLITIQUE RELATIVE À LA PROTECTION DES DONNÉES À CARACTÈRE PERSONNEL, MAIS AUSSI Y AJOUTER OU EN RETRANCHER DES ÉLÉMENTS CHAQUE FOIS QUE NOUS LE JUGERONS UTILE ET SANS AVERTISSEMENT. Tout changement sera publié sur cette page afin que vous soyez pleinement informé du type de données que nous recueillons, de l’utilisation que nous en faisons et des conditions dans lesquelles elles peuvent être publiées.</p>
        <p>Notre Politique relative à la protection des données à caractère personnel est facile à trouver : elle figure sur notre page d’accueil et un lien permettant d’y accéder figure sur chaque page du site sur laquelle il faut remplir des données personnelles. Lorsque de telles données sont demandées, des explications détaillées sont fournies sur l’utilisation qui en sera faite chaque fois que cela s’impose. La Politique, ainsi que toute explication supplémentaire, détaille la manière dont nous traitons chaque donnée que vous fournissez spontanément dans le cadre de votre utilisation du site internet.  </p>
        <p>
          1. Engagement de respect de la vie privée  <br />
            L’expression « données à caractère personnel » utilisée dans la présente Politique s’applique à diverses informations (nom, date de naissance, adresse e-mail, adresse postale, numéro de téléphone ou adresse IP) susceptibles d’être utilisées pour vous identifier. De manière générale, nous ne traitons pas vos données à caractère personnel sans votre autorisation. Nous nous réservons cependant le droit, dans des circonstances exceptionnelles, d’effectuer un traitement supplémentaire dans la mesure permise ou requise par la législation ou dans le cadre d’une enquête judiciaire ou criminelle.    </p>
        <p>
            Les chapitres suivants détaillent la manière dont nous recueillons les données à caractère personnel et les moments où nous le faisons.
        </p>
        <p>
            2.  Fins auxquelles les données à caractère personnel sont recueillies  <br />
Lorsque vous vous enregistrez sur notre site Internet, vous devez remplir un certain nombre de champs (certains obligatoires et d’autres facultatifs) et choisir un nom d’utilisateur ainsi qu’un mot de passe. Si vous décidez de ne pas communiquer certaines des données exigées, il se peut que vous ne puissiez pas accéder à certaines pages du site ou que nous soyons dans l’impossibilité de répondre à une éventuelle demande de votre part.</p>
        <p>Nous traitons les données à caractère personnel aux fins dont nous vous avons informé au moment où nous vous avons demandé de nous communiquer ces données. Nous conservons vos données conformément à toutes les obligations juridiques ou éthiques applicables en matière de conservation de rapports ou de documents.     </p>
        <p>
            3.Non-communication d’informations   <br />
            Nous ne vendons pas, ne partageons pas ni ne distribuons autrement vos données à caractère personnel à des tiers, sauf dans les cas prévus dans la présente Politique. Des données à caractère personnel peuvent occasionnellement être transférées à des tiers qui agissent pour MS Nurse Professional, ou pour le compte de celle-ci, en vue d'un traitement supplémentaire conformément aux fins auxquelles les données ont été initialement recueillies : prestation de services, évaluation ou soutien technique. Ces tiers se sont engagés par contrat auprès de MS Nurse Professional à utiliser les données à caractère personnel uniquement aux fins convenues et à ne pas vendre ni divulguer ces données à des tiers, sauf si la loi l'exige. En cas de communication des données à caractère personnel à des tiers, nous veillons à ce que ces données soient traitées conformément aux fins auxquelles elles ont été initialement recueillies et conformément au cadre dans lequel elles l’ont été.      </p>
        <p>
            Les données à caractère personnel peuvent être communiquées à des tiers dans deux autres cas encore. Il y a d’abord l’éventualité où les activités de ce site et les données relatives aux clients qu’il contient sont vendues, cédées ou transférées ; le cas échéant, nous exigerons de l’acheteur ou du cessionnaire de traiter ces données conformément à la présente Politique. La seconde éventualité concerne l’obligation dans laquelle nous serions de communiquer des données à caractère personnel à un tiers en application d’une loi, d’une ordonnance du tribunal ou d’une réglementation d’un gouvernement, ou leur publication dans le cadre d’une enquête judiciaire ou criminelle.        </p>
        <p>
            4.  Droit d’accès  <br />
            Vous avez le droit de vous assurer que vos données à caractère personnel sont toujours à jour. Dans certains pays, vous avez le droit de nous demander de rectifier ou de supprimer vos données à caractère personnel. Vous pouvez également nous demander à tout moment de cesser de vous contacter. Si vous souhaitez communiquer avec nous au sujet de l'utilisation que nous faisons de vos données à caractère personnel, veuillez envoyer un courrier à MS Nurse Professional, TBC. Si vous nous contactez, veuillez indiquer les informations que vous nous demandez de rectifier, d’actualiser ou de supprimer. Toute demande sera traitée dans les plus brefs délais et de manière appropriée. Toute demande de suppression de données à caractère personnel est soumise aux obligations juridiques ou éthiques en matière d'archivage ou de conservation des rapports ou documents qui nous sont imposées.     </p>
        <p>
            5. Sécurité et confidentialité <br />
           En vue d’assurer la sécurité et la confidentialité des données à caractère personnel recueillies en ligne, nous utilisons des réseaux protégés notamment par des pare-feux et des mots de passe conformes aux normes sectorielles. Pour le traitement de vos données à caractère personnel, nous prenons des mesures raisonnables en vue de protéger ces données contre la perte, l'usage à mauvais escient, l'accès non autorisé, la communication, la modification ou la destruction. Si nous ne pouvons donner de garanties
            relativement à la perte, à l'usage à mauvais escient, ni à l'accès, à la divulgation, à la modification ou à la destruction non autorisés de ces données, nous tentons d'empêcher que ces malheureux incidents se produisent.
        </p>
        <p>
            6.Transfert de données à l’étranger    <br />
           Nous pouvons transférer vos données à caractère personnel à des bases de données situées en dehors des frontières de votre pays. Même si le pays vers lequel les données doivent être transférées n’exige pas que nous en assurions une protection correcte, nous veillerons néanmoins à nous assurer que les transferts de données dans ce pays soient protégés de manière appropriée et que la communication de ces données à des tiers dans ce pays ne puisse pas se faire sans votre autorisation expresse préalable.       </p>
        <p>
            7. Données anonymes et « cookies »   <br />
           Nous pouvons recueillir et traiter des informations anonymes concernant votre visite sur le présent site Internet, notamment les pages que vous visitez et les recherches que vous effectuez. Nous nous servons de ces informations anonymes pour améliorer le contenu du site et compiler des statistiques globales au sujet des personnes qui utilisent notre site à des fins internes et d’étude de marché. Ce faisant, nous pouvons installer des « cookies » qui recueillent le premier niveau de nom de domaine de l’utilisateur (par exemple : « bigmail.com » tiré de l’adresse de « jean@bigmail.com ») ainsi que la date et l’heure de l’accès. Tels que nous les utilisons, les « cookies » ne peuvent servir à découvrir l’identité de l’utilisateur individuel. Les « cookies » sont de petits fichiers envoyés sur votre navigateur et installés sur le disque dur de votre ordinateur. Ils n’endommagent pas votre ordinateur. Vous pouvez paramétrer votre navigateur pour qu’il vous avertisse de la réception d’un « cookie », ce qui vous permet de décider si vous voulez l’accepter ou non. Nous pouvons recourir aux services de tiers pour nous aider à recueillir et à traiter les données citées dans la présente rubrique et ces tiers seront soumis aux obligations susmentionnées à la rubrique 3. À l’occasion, nous pouvons utiliser des marqueurs Internet (aussi appelés Action Tags, Single-Pixel GIFs, Clear GIFs, Invisible GIFs et 1-by-1 GIFs) conjointement avec des cookies sur le présent site et nous pouvons déployer ces marqueurs par l’intermédiaire d’un partenaire publicitaire. Ces marqueurs sont placés sur les annonces en ligne qui amènent des utilisateurs vers le site et sur différentes pages du site. Nous utilisons cette technologie pour mesurer les réponses des visiteurs à nos sites et l’efficacité de nos campagnes publicitaires (y compris le nombre d’accès à une page ainsi que les informations consultées). Le tiers peut être en mesure de recueillir des données globales anonymes sur les visiteurs d’autres sites au moyen de ces marqueurs/cookies. Soyez assuré que nous NE recueillons PAS, ni ne cherchons à le faire, des informations permettant d’identifier nos visiteurs (nom, adresse, adresse e-mail ou numéro de téléphone) au moyen de ces marqueurs ou cookies.      </p>
        <p>
            8. Données à caractère personnel et enfants <br />
           La plupart des services proposés sur le présent site sont destinés à des personnes âgées de 18 ans minimum. Nous ne recueillons pas, n’utilisons pas ni ne communiquons sciemment de données à caractère personnel concernant un mineur sans le consentement préalable d’une personne exerçant une autorité parentale (père, mère ou tuteur) obtenu au
            moyen d’un contact direct hors ligne. Nous donnons aux parents (i) une liste du type précis des données à caractère personnel recueillies auprès du mineur et (ii) la possibilité de s’opposer à toute collecte, toute utilisation ou tout enregistrement ultérieurs de ces informations. Nous respectons la législation relative à la protection des enfants.
        </p>
        <p>
            9. Liens vers d’autres sites   <br />
            La présente Politique relative à la protection des données à caractère personnel ne s’applique qu’au présent site Internet à l’exclusion des sites de tiers. Nous pouvons fournir des liens vers d’autres sites Internet dont nous pensons qu’ils peuvent présenter un intérêt pour nos visiteurs. Nous visons à nous assurer que ces sites respectent les normes les plus strictes. Toutefois, en raison de la nature du Web, nous ne pouvons garantir les normes de protection des données à caractère personnel de chaque site que nous mettons en lien ni ne pouvons être responsables du contenu de sites autres que le présent site, et cette Politique n’est pas destinée à s’appliquer à d’autres sites.       </p>
        <p>
            10. Contactez-nous <br />
           En cas de question ou de plainte au sujet du respect de la présente Politique relative à la protection des données à caractère personnel, ou si vous souhaitez formuler des recommandations ou des commentaires pour améliorer la qualité de cette politique, veuillez envoyer un courrier à Privacy Policy Administrator, MS Nurse Professional.        </p>
        <p>
            Politique relative à la protection des données à caractère personnel – Dernière mise à jour : septembre 2012
        </p>
    </div>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="wrapperContent" Runat="Server">
</asp:Content>

