<%@ Page Title="" Language="C#" MasterPageFile="~/masterpages/frontend.master" AutoEventWireup="true" CodeFile="terms-fr.aspx.cs" Inherits="terms_fr" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="contentBreadcrumb" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="contentMain" Runat="Server">
    <div class="terms">
        <h1> CONDITIONS GÉNÉRALES D’UTILISATION DU SITE INTERNET</h1>
        <p>Par votre utilisation du présent site Internet, vous acceptez les conditions générales d’utilisation ci-après, celles-ci formant un contrat entre MS Nurse Professional et vous-même. Ces conditions sont susceptibles d’être modifiées. Leur version la plus récente peut être consultée en cliquant sur le lien au bas de chaque page du site.     </p>
        <p>Veuillez prendre note des protections suivantes s’appliquant aux informations, services, produits ou messages présentés sur ce site Internet. Ces conditions d’utilisation s’appliquent à votre usage du site. Lorsque vous le quittez pour vous rendre sur un autre site (d’un tiers), d’autres conditions peuvent s’appliquer.    </p>
        <p>
            1. Acceptation
            Votre accès au site et votre utilisation de celui-ci sont soumis aux conditions ci-après ainsi qu’à toutes les lois en vigueur. Par votre accès au site et votre navigation sur celui-ci, vous indiquez que vous êtes âgé de 18 ans minimum et que vous acceptez ces conditions générales sans restriction ni réserve.      </p>
        <p>
            2. Informations
            Les informations que contient le site sont fournies par MS Nurse Professional et destinées à des professionnels de la santé diplômés et majeurs. Une information sur un produit ne vise pas à délivrer un avis médical ou à s’y substituer. Les visiteurs du site doivent s’adresser à des services médicaux locaux s’ils souhaitent un avis sur leur santé. Si vous êtes un consommateur et que vous décidez d’utiliser les informations d’un niveau professionnel fournies par ce site, vous ne pouvez pas les assimiler à un avis médical ou les utiliser en remplacement d’une relation avec votre généraliste ou tout autre professionnel qualifié du secteur de la santé. Pour tout ce qui concerne l’aspect médical, notamment des décisions concernant des médicaments et autres traitements, les consommateurs doivent systématiquement consulter leur médecin généraliste ou, dans les cas les plus graves, se rendre immédiatement aux urgences.       </p>
        <p>Ce site Internet est financé par le biais d’une subvention à l’éducation accordée par Novartis Pharma AG. Le soutien accordé à ce site internet n’implique pas pour autant une adhésion aux idées formulées sur ce site.       </p>
        <p>
            3. Utilisation des informations
            Vous pouvez naviguer librement sur le site, mais l’accès aux données qui y sont mentionnées, leur téléchargement ou leur utilisation sont autorisés à des fins d’information générale uniquement. Vous ne pouvez pas diffuser, modifier, transmettre, réutiliser, republier ou utiliser ces données à des fins commerciales. Vous devez garder et reproduire chaque mention du droit d’auteur ou d’autres droits de propriété cités dans les informations que vous téléchargez. Vous devez partir du principe que tout ce que vous voyez ou lisez sur le site est couvert par le droit d’auteur, sauf mention contraire, et ne peut être utilisé, sauf disposition contraire des présentes conditions générales ou du texte du site, sans l’autorisation écrite de MS Nurse Professional. MS Nurse Professional ne garantit ni n’affirme que votre utilisation du contenu du site n’enfreindra pas les droits de tiers. Aucune licence ni aucun droit relatif aux informations, aucun droit d’auteur ne vous est accordé par MS Nurse Professional ou toute autre partie.      </p>
        <p>
            4. Marques/droits de propriété
            Vous devez partir du principe que tous les noms de produits figurant sur ce site, qu'ils apparaissent ou non en gros caractères ou accompagnés du symbole de la marque, sont des marques déposées. Ce site peut également contenir ou citer des brevets, renseignements confidentiels, technologies, produits, procédés ou autres droits de propriété appartenant à des tiers. Aucune licence ni aucun droit sur ces marques, brevets, secrets commerciaux, technologies, produits, procédés et autres droits de propriété ne vous sont accordés.       </p>
        <p>
            5. Exclusion de garanties
           MS Nurse Professional déploie des efforts raisonnables pour assurer l'exactitude et la mise à jour des informations présentées sur ce site, elles sont néanmoins susceptibles de contenir des inexactitudes techniques ou des erreurs typographiques. MS Nurse Professional se réserve le droit d'apporter des modifications, des corrections ou des améliorations aux informations, aux produits et aux programmes décrits dans ces informations, à tout moment et sans préavis. MS Nurse Professional ne fournit aucune garantie ou déclaration quant à l'exactitude de ces informations. MS Nurse Professional décline toute responsabilité en cas d’erreur ou d’omission dans le contenu du site. TOUTES LES INFORMATIONS SONT FOURNIES « TELLES QUELLES ». MS Nurse Professional NE DONNE AUCUNE GARANTIE QUANT À L'EXHAUSTIVITÉ OU À L'EXACTITUDE DES INFORMATIONS SUR CE SITE OU LEURS UTILISATIONS POSSIBLES. EN CONSÉQUENCE, LES VISITEURS DU SITE DOIVENT SOIGNEUSEMENT ÉVALUER CES INFORMATIONS. AUCUNE AUTRE PARTIE IMPLIQUÉE DANS LA CRÉATION, LA PRODUCTION OU LA LIVRAISON DE CE SITE NE POURRA ÊTRE TENUE RESPONSABLE DES DOMMAGES OU PERTES DIRECTS, ACCIDENTELS, CONSÉCUTIFS OU INDIRECTS DÉCOULANT DE L'ACCÈS À CE SITE, DE SON UTILISATION OU DE L'INCAPACITÉ DE L'UTILISER, NI DES ERREURS OU OMISSIONS DANS LE CONTENU DU SITE. De même, MS Nurse Professional n'assume aucune responsabilité et ne peut être tenue responsable en cas de dommage subi par votre équipement informatique (virus, etc.) ou autre propriété du fait de l'accès aux informations et de leur utilisation. MS Nurse Professional se réserve le droit de supprimer le site à tout moment, sans avertissement et sans engagement de sa responsabilité.    </p>
        <p>
            6. Informations fournies par vos soins
            À l’exception des informations couvertes par notre politique relative à la protection des données à caractère personnel, toute information communiquée sur le site par courrier électronique ou tout autre moyen, notamment les données, questions, commentaires, suggestions ou assimilé, sera considérée comme non confidentielle et non propriétaire. Tout ce que vous envoyez devient la propriété de MS Nurse Professional et peut être utilisé à toutes fins utiles, entre autres mais sans s’y limiter, la reproduction, la mention, la transmission, la publication, la diffusion et l’affichage. Par ailleurs, MS Nurse Professional est libre d'utiliser, sans compensation pour vous, l’ensemble des idées, concepts, savoir-faire ou techniques contenus dans les messages envoyés sur le site pour quelque but que ce soit, notamment mais sans s’y limiter le développement, la fabrication et le marketing des produits utilisant ces informations.       </p>
        <p>
            7.Absence de promotion
            Aucun élément de ce site ne peut être considéré comme une promotion ou une publicité pour un produit ou l’utilisation d’un produit non autorisé aux termes de la législation et de la réglementation en vigueur dans votre pays.       </p>
        <p>
            8. Liens vers ce site
            MS Nurse Professional n’a vérifié aucun des sites Internet de tiers qui contiennent un lien vers le présent site et ne peut être tenue responsable du contenu de ces pages externes ou de tout autre site lié à celui-ci. Si vous souhaitez ajouter à votre site un lien vers celui de MS Nurse Professional, vous ne pouvez insérer qu’un lien vers la page d’accueil. Vous n’êtes pas autorisé à mettre un lien renvoyant vers d’autres pages du site sans l’autorisation écrite préalable de MS Nurse Professional. Toute citation ou utilisation d’une ou plusieurs parties de ce site sur le site d’un tiers en l’absence de cette autorisation écrite est pareillement interdite.       </p>
        <p>
            9. Liens vers d’autres sites
            Des liens vers des sites tiers peuvent être fournis pour l'intérêt ou la commodité des visiteurs de ce site. Nous essayerons de vous informer lorsque vous quittez ce site que les conditions d'utilisation et la politique relative à la protection des données à caractère personnel du site tiers peuvent être différentes. Toutefois, MS Nurse Professional n'assume aucune responsabilité concernant les liens renvoyant vers d’autres sites, et en particulier concernant l'exactitude ou la légalité du contenu de ces sites tiers. Nous déclinons toute responsabilité résultant d’une violation ou d’une omission concernant les politiques de protection des données à caractère personnel de tiers.        </p>
        <p>
            10. Commentaires sur ce site
            Bien que MS Nurse Professional puisse périodiquement surveiller ou relire des discussions, des chats, des posts, des transmissions, des panneaux d’affichage et autres messages sur le site, MS Nurse Professional n’a aucune obligation en la matière et rejette toute responsabilité découlant du contenu de ces informations, ou quant à l’un des éléments suivants : erreur, diffamation, calomnie, omission, mensonge, obscénité, pornographie, blasphème, danger, violation de la protection des données à caractère personnel ou inexactitude dans les informations présentées par les messages postés sur le site. Vous ne pouvez pas poster ou transmettre de matériel illégal, menaçant, diffamatoire, obscène, scandaleux, incendiaire, pornographique ou blasphématoire ou de matériel qui pourrait constituer ou encourager une conduite considérée comme une infraction pénale, engager une responsabilité civile ou violer une loi de toute autre manière. MS Nurse Professional coopérera pleinement avec toute autorité judiciaire ou ordonnance d'un tribunal demandant ou ordonnant à MS Nurse Professional de divulguer l'identité de toute personne publiant de tels renseignements ou contenus.       </p>
        <p>
            11. Conséquences
            Si nous apprenons que vous avez violé l’une des conditions citées dans les présentes mentions légales, nous sommes en droit de prendre des mesures correctives, notamment empêcher l’utilisateur d’utiliser les services proposés par MS Nurse Professional et supprimer toute information, toute donnée et tout contenu publiés sur le site par l’utilisateur, à tout moment et sans avertissement. Si nous sommes lésés par votre infraction, nous pouvons décider d’exiger des dommages et intérêts de votre part.        </p>
        <p>
            12. Révisions
            MS Nurse Professional se réserve le droit de réviser ces conditions générales en actualisant cette page. Vous êtes tenu de respecter ces révisions et devez par conséquent consulter régulièrement la page de manière à disposer de la version la plus récente des conditions générales en vigueur.        </p>
        <p>
            Dernière révision : septembre 2012
        </p>
    </div>
</asp:Content>

